#! /bin/bash

case "$1" in
  start|Start)
    echo "Start"
    /tmp/sleepwalkingserver &
  ;;
  stop|Stop)
    echo "Stop"
    kill $(cat /tmp/sleepwalkingserver.pid)
  ;;
  *)
    echo "Usage sleepwalking start/stop"
    exit 1
esac